server:
  port: 8080
  
app:
  cat-fact:
    api-url: https://catfact.ninja/fact
    timeout: 5000
    
logging:
  level:
    com.haidara.profileapi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

profile:
  email: "aliyuatk@gmail.com"
  name: "Aliyu Tukur"
  stack: "Java/Spring Boot"
